### PR TITLE
Draft readme update

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**

### CODE REVIEW

**Review by aknguyen7 — DISMISSED** [review]

**Comment by Sreejith-Websphere** [comment]
As per @mbroz comment docs team no longer needs to make changes to the openliberty.io repo, then they should no longer need to open PRs so we don't need steps to follow in open liberty repo

**Review by dmuelle — COMMENTED** [review]
why is the draft version different from whats in prod? 
It looks like this version is missing the step to update the antora yaml in docs-generated (step 7. on prod) and there are discrepancies at step 4. I would think you could just duplicate what we have on prod to draft and staging since the directions will likely only ever be viewed on prod anyway.

**Comment by Sreejith-Websphere** [comment]
ok thanks @dmuelle I will use same content as in prod for draft and staging

**Comment by kinueng** [comment]
RE: https://github.com/OpenLiberty/docs-playbook/pull/185#issuecomment-1125076508

@Sreejith-Websphere the `prod` branch now has the updated `README.md`. Please make this PR and https://github.com/OpenLiberty/docs-playbook/pull/186 match the prod's README.md (https://github.com/OpenLiberty/docs-playbook/pull/187/commits/e3c7f3e6f82025299f0f8d96625403414871fc74)

**Comment by Sreejith-Websphere** [comment]
added content same as prod along with mbroz changes

**Review by mbroz2 — CHANGES_REQUESTED** [review]
Please update with the latest contents of prod as delivered via https://github.com/OpenLiberty/docs-playbook/pull/192/files

**Comment by Sreejith-Websphere** [comment]
added with latest content

**Review by mbroz2 — APPROVED** [review]

**Pull request merged**
