### PR TITLE
Staging readme update

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**

### CODE REVIEW

**Review by aknguyen7 — DISMISSED** [review]

**Comment by Sreejith-Websphere** [comment]
As per @mbroz comment docs team no longer needs to make changes to the openliberty.io repo, then they should no longer need to open PRs so we don't need steps to follow in open liberty repo

**Comment by Sreejith-Websphere** [comment]
updated content as per prod along with mbroz changes

**Review by mbroz2 — CHANGES_REQUESTED** [review]
Please update with the latest contents of prod as delivered via https://github.com/OpenLiberty/docs-playbook/pull/192/files

**Comment by Sreejith-Websphere** [comment]
added with latest changes

**Review by mbroz2 — APPROVED** [review]

**Pull request merged**
